[package]
name = "aoc24"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
dotenvy = "0.15.7"
tokio = { version = "1.41.1", features = ["full"] }
rayon = "1.10.0"
reqwest = "0.12.9"
anyhow = "1.0.93"
microbench = "0.5.0"